### ISSUE TITLE
FAILED to unzip ...

### ISSUE THREAD

**Issue by mkoskar** [gaenserich/hostsblock#27] opened 2015-04-27 17:42 UTC
First run works OK, subsequent one returns following:

    $ sudo /usr/bin/hostsblock
    [/var/cache/hostsblock/hosts-file.net.download.hosts.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of /var/cache/hostsblock/hosts-file.net.download.hosts.zip or
            /var/cache/hostsblock/hosts-file.net.download.hosts.zip.zip, and cannot find /var/cache/hostsblock/hosts-file.net.download.hosts.zip.ZIP, period.
    [WARN] FAILED to unzip hosts-file.net.download.hosts.zip.
    [/var/cache/hostsblock/hostsfile.org.Downloads.BadHosts.unx.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of /var/cache/hostsblock/hostsfile.org.Downloads.BadHosts.unx.zip or
            /var/cache/hostsblock/hostsfile.org.Downloads.BadHosts.unx.zip.zip, and cannot find /var/cache/hostsblock/hostsfile.org.Downloads.BadHosts.unx.zip.ZIP, period.
    [WARN] FAILED to unzip hostsfile.org.Downloads.BadHosts.unx.zip.
    [/var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of /var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip or
            /var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip.zip, and cannot find /var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip.ZIP, period.
    [WARN] FAILED to unzip winhelp2002.mvps.org.hosts.zip.

PS: I've found this problem reported in Arch Forums `hostsblock` thread too but thought it's better to track it here.

**Comment by gaenserich** [comment] 2015-04-27 18:10
I have seen this, too in my testing. I suspect that the upstream site hosting the blacklist may be failing somehow and sending an error file (which overwrites the local cached copy) instead of letting curl fail gracefully. When you get this message once again, could you try to download the errarant files manually in your browser?

If you can't download them manually, this means that there is an upstream problem (the hosting site is down) which we need to take account of (make curl fail instead of overwriting the cache file). If you can download it manually, we might have a bigger issue.

**Comment by mkoskar** [comment] 2015-04-27 19:11
Without looking into source, reason for this which I thought of was that `curl` is actually taking HTTP validators (`If-Modiefied-Since` etc.) into account, and since nothing has changed result is empty and such is incorrectly written to the result file, confusing the rest of process.

I've actually verified that by running `$ sudo /usr/bin/hostsblock -v 5`, and e.g., one response looks like this:

    [DETAIL] Url file for /var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip present.
    [DETAIL] Cache file /var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip for blocklist http://winhelp2002.mvps.org/hosts.zip exists. Noting its modification time.
    [DETAIL] Checking and, if needed, downloading blocklist http://winhelp2002.mvps.org/hosts.zip to /var/cache/hostsblock/winhelp2002.mvps.org.hosts.zip
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 216.155.126.40...
    * Connected to winhelp2002.mvps.org (216.155.126.40) port 80 (#0)
    > GET /hosts.zip HTTP/1.1
    > Host: winhelp2002.mvps.org
    > User-Agent: curl/7.42.0
    > Accept: */*
    > Accept-Encoding: deflate, gzip
    > If-Modified-Since: Mon, 27 Apr 2015 18:31:11 GMT
    > 
    < HTTP/1.1 304 Not Modified
    < Date: Mon, 27 Apr 2015 18:31:27 GMT
    < Etag: "ea4ffd53216cd01:0"
    < 
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    * Connection #0 to host winhelp2002.mvps.org left intact
    [INFO] Refreshed blocklist http://winhelp2002.mvps.org/hosts.zip.
    [NOTE] CHANGES FOUND for blocklist http://winhelp2002.mvps.org/hosts.zip.

I guess that last line actually indicates problem already, since in reality there are no changes.
I did simple testing and I'm surprised that cURL will rewrite output file on HTTP 304:

    curl http://winhelp2002.mvps.org/hosts.zip -o hosts.zip -z hosts.zip -s -L -w '%{http_code}\n'

So first time it downloads correctly, subsequently on 304, output file will be truncated. I didn't find obvious way how to tell cURL to not do that. Probably we could just do something like:

    if curl_status=$(curl $_v_curl --compressed --connect-timeout $connect_timeout --retry $retry -z "$cachedir"/"$_outfile" "$_url" -o "$cachedir"/"${_outfile}.curl" -w '%{http_code}'); then
        case $curl_status in
            200)
                cp -a "${_outfile}.curl" "$_outfile"
                # process "$_outfile"
                ;;
            304)
                # nothing to do
                ;;
            *)
                # something went wrong
                ;;
        esac
    fi

**Comment by gaenserich** [comment] 2015-04-28 01:11
Ug. Curl is supposed to not pull this malarky! Namely, the -z option is supposed to prevent this behavior:
`man curl`:
```
        -z, --time-cond <date expression>|<file>
              (HTTP/FTP) Request a file that has been modified later than the given time and date,
              or  one  that  has  been modified before that time. The <date expression> can be all
              sorts of date strings or if it doesn't match any internal ones, it  is  taken  as  a
              filename and tries to get the modification date (mtime) from <file> instead. See the
              curl_getdate(3) man pages for date expression details.

              Start the date expression with a dash (-) to make it request for a document that  is
              older  than the given date/time, default is a document that is newer than the speci‐
              fied date/time.

              If this option is used several times, the last one will be used.
```
Supposedly curl should handle this on its own as it is currently configured in `hostsblock`, at least that's what I thought the -z option was supposed to do.

**Comment by gaenserich** [comment] 2015-04-28 01:14
I'm seeing this too for all of my blocklists too. `hostsblock` didn't do this before, I'm thinking it's a regression of some sort. :-/

**Comment by mkoskar** [comment] 2015-04-28 08:21
Yes it's weird, but `-z` doesn't really say that it doesn't change the output file, though that would be something to be reasonably expected. I went and simple tested `curl` for regression since I saw it got updated recently:

    :0:tmp$ curl http://winhelp2002.mvps.org/hosts.zip -o hosts.zip -z hosts.zip -s -w '%{http_code}\n'
    Warning: Illegal date format for -z, --timecond (and not a file name).
    Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
    200

    +0:tmp$ la
    total 136K
    -rw-r--r-- 1 miro miro 136K Apr 28 10:12 hosts.zip

    +0:tmp$ curl http://winhelp2002.mvps.org/hosts.zip -o hosts.zip -z hosts.zip -s -w '%{http_code}\n'
    304

    +0:tmp$ la
    total 0
    -rw-r--r-- 1 miro miro 0 Apr 28 10:12 hosts.zip

    # downgrading package curl (7.42.0-1 => 7.41.0-1)

    +0:tmp$ rm hosts.zip

    +0:tmp$ curl http://winhelp2002.mvps.org/hosts.zip -o hosts.zip -z hosts.zip -s -w '%{http_code}\n'
    Warning: Illegal date format for -z, --timecond (and not a file name).
    Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
    200

    +0:tmp$ la
    total 136K
    -rw-r--r-- 1 miro miro 136K Apr 28 10:13 hosts.zip

    +0:tmp$ curl http://winhelp2002.mvps.org/hosts.zip -o hosts.zip -z hosts.zip -s -w '%{http_code}\n'
    304

    +0:tmp$ la
    total 136K
    -rw-r--r-- 1 miro miro 136K Apr 28 10:13 hosts.zip

So it's clearly `curl` to blame here. I'll look around if there is not some bug-report laying around. I plan on reporting against ArchLinux and upstream. Will post links here later.

**Comment by mkoskar** [comment] 2015-04-28 08:45
Ok, this `curl` issue has been fixed upstream (see https://github.com/bagder/curl/issues/237). Also in https://github.com/bagder/curl/issues/240 somebody shared that "7.43.1 will be released this week". I suggest to wait for that and verify issue went away.

**Comment by gaenserich** [comment] 2015-04-28 18:03
Good. Thanks for the legwork on this one. We'll keep an eye on it and close this is it turns out to be all curl's issue.

**Comment by gaenserich** [comment] 2015-05-19 12:53
@mkoskar: My distro hasn't updated to curl 7.42.1 yet. Has yours and if so, has it fixed the issue?

**Comment by mkoskar** [comment] 2015-05-20 22:40
@gaenserich I use ArchLinux and 7.42.1 is released into Testing for some time already. I don't use Testing, but did install it and issue is fixed. I did delete cache directory for start, and tried to run `hostsblock` couple time in sequence without errors. Also looking into cache directory, files have proper (non-zero) sizes.

**Closed** 2015-05-21 14:21 UTC
